### ISSUE TITLE
Installed Git 2.2.1 Fails, OS X 10.8.5

### ISSUE THREAD

**Issue by RGBboy** [timcharper/git_osx_installer#22]
I get this error when installing the latest build on my mac running OSX 10.8.5.

```
dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/git/bin/git
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /usr/local/git/bin/git
  Expected in: /usr/lib/libSystem.B.dylib
```

Looks like it is related to #16.
