### ISSUE TITLE
Git does not work in Mac Version 10.10.3 

### ISSUE THREAD

**Issue by elivaquera** [timcharper/git_osx_installer#52]
Install does not work. It does all the steps, but then I have no access to the program and I can't find it anywhere. Odd.

**Comment by tzachariah** [comment]
![screen shot 2015-06-20 at 5 50 32 pm](https://cloud.githubusercontent.com/assets/12416832/8269904/15b79250-1775-11e5-9392-8660f0501acf.png)

**Comment by slauderdale** [comment]
@elivaquera - did you ever figure this out?  HAving same issue

**Comment by AbdullahRefaey** [comment]
Hi,
I am trying to install Gate7.1, but it is stopped:
In file included from /home/abdullah/Gate/opt/simulation/gate_v7.1/source/digits_hits/src/GateFragmentationAndProductionActor.cc:14:0:/home/abdullah/Gate/opt/simulation/gate_v7.1/source/digits_hits/include/GateFragmentationAndProductionActor.hh:22:22: fatal error: TVector2.h: No such file or directory #include "TVector2.h" ^compilation terminated.CMakeFiles/Gate.dir/build.make:7207: recipe for target 'CMakeFiles/Gate.dir/source/digits_hits/src/GateFragmentationAndProductionActor.cc.o' failedmake[2]: *** [CMakeFiles/Gate.dir/source/digits_hits/src/GateFragmentationAndProductionActor.cc.o] Error 1CMakeFiles/Makefile2:619: recipe for target 'CMakeFiles/Gate.dir/all' failedmake[1]: *** [CMakeFiles/Gate.dir/all] Error 2Makefile:127: recipe for target 'all' failedmake: *** [all] Error 2
 could you help please?


Yours,

Abdullah A. Refaey

Positron Annihilation Laboratory
Physics department, Faculty of Science
Minia University, Egypt.
Home Phone: (+2045) 664 562 Work Phone: (+2086) 236 3011 
Fax: (+2086) 2363011 Mobile: (+2010) 0708 3430
